version: '3.7'

services:
  ml:
    build:
      context: ./ml
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000"
    expose:
      - 8000
#    ports:
#      - 8003:8000
  backend:
    build:
      context: ./backend
    command: sh -c "python3 manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:8080 --timeout 10000 project.wsgi"
    expose:
      - 8080
    volumes:
      - ./backend:/usr/src/avia
    environment:
      - DEBUG=True
      - SECRET_KEY=DJANGO_SECRET_KEY
#    external_links:
#      - ml
  frontend:
    build:
      context: ./frontend
    command: npm run-script build
    volumes:
      - frontend_build_folder:/frontend/build
    environment:
      - REACT_APP_PRODUCTION_URL=http://127.0.0.1/
  nginx:
    build:
      context: ./nginx
    ports:
      - 80:8080
    volumes:
      - frontend_build_folder:/var/www/frontend
      - ./backend:/usr/src/avia
    depends_on:
      - ml
      - backend
      - frontend
volumes:
  frontend_build_folder: