version: '3.7'

services:
  backend:
    build:
      context: ./backend
    command: sh -c "pip install -r requirements.txt && python3 manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:8080 project.wsgi"
    expose:
      - 8080
    volumes:
      - ./backend:/usr/src/avia
    environment:
      - DEBUG=False
      - SECRET_KEY=DJANGO_SECRET_KEY
#  frontend:
#    build:
#      context: ./frontend
#    command: npm run-script build
#    volumes:
#      - frontend_build_folder:/frontend/build
#    environment:
#      - REACT_APP_PRODUCTION_URL=http://127.0.0.1:8001/
  nginx:
    build:
      context: ./nginx
    ports:
      - 80:8080
    volumes:
#      - frontend_build_folder:/var/www/frontend
      - ./backend:/usr/src/avia
    depends_on:
      - backend
#      - frontend
#volumes:
#  frontend_build_folder: