# Generated by Django 3.2 on 2021-04-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_message_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='json',
            field=models.CharField(default='', max_length=1000000, verbose_name='JSON'),
        ),
    ]
