# Generated by Django 3.2 on 2021-04-25 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210425_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='correct',
            field=models.FileField(null=True, upload_to='', verbose_name='correct'),
        ),
        migrations.AddField(
            model_name='message',
            name='incorrect',
            field=models.FileField(null=True, upload_to='', verbose_name='incorrect'),
        ),
        migrations.AlterField(
            model_name='message',
            name='answer',
            field=models.FileField(null=True, upload_to='', verbose_name='answer'),
        ),
    ]
