# Generated by Django 3.2 on 2021-04-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_message_kml'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='num_correct',
            field=models.IntegerField(null=True, verbose_name='num cor'),
        ),
        migrations.AddField(
            model_name='message',
            name='num_incorrect',
            field=models.IntegerField(null=True, verbose_name='num incor'),
        ),
    ]
