# Generated by Django 3.2 on 2021-04-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20210425_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='num_correct',
            field=models.IntegerField(default=0, null=True, verbose_name='num cor'),
        ),
        migrations.AlterField(
            model_name='message',
            name='num_incorrect',
            field=models.IntegerField(default=0, null=True, verbose_name='num incor'),
        ),
    ]
